name: OH music
favicon: null
layout_spectrum: 0.9754673296120018
typography_spectrum: 0.06978
title: OH Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f09354'
    - '#ed7a2c'
    - '#fadeca'
    - '#f3ac7b'
  brandStrength: 1
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
